# Settings.toml

# Redis Cluster Configuration
# Redis is used as the share store currently
redis_pool_max_size = "1500"
cluster_nodes = ["redis://:0rangerY@127.0.0.1:6380", "redis://:0rangerY@127.0.0.1:6381", "redis://:0rangerY@127.0.0.1:6382"]

#Substrate-Blockchain Configuration
substrate.ws_url = "ws://127.0.0.1:9944"

#Secret Sharing Configuration
chunk_size = 48
threshold = 2
share_amount = 3
prime = "1602647667098023157650208502760830646118971559180602279760560620305846622963164828915087516998772696148300120393034934719"
thread_number = 5


#[account]
#name = "Alice"

#"error" => tracing::Level::ERROR,
#"warn" => tracing::Level::WARN,
#"info" => tracing::Level::INFO,
#"debug" => tracing::Level::DEBUG,
#"trace" => tracing::Level::TRACE,
[logging]
level = "warn"
module_filter = [
    "graymamba::sharesfs::channel_buffer=debug",
    "graymamba::sharesfs::writing=debug",
    "graymamba::sharesfs::directories=debug",
    "graymamba::sharesfs::rename=debug",
    "graymamba::kernel=debug",
    "data_room=debug",
    #"graymamba::backingstore::rocksdb_data_store=debug"
    ]

[storage]
rocksdb_path = "../RocksDBs/graymamba"
auditdb_path = "../RocksDBs/audit_merkle_db"

[nfs]
data_room_address = "127.0.0.1:2049"
