# Settings.toml

# Redis Cluster Configuration
# Redis is used as the share store currently
redis_pool_max_size = "1500"
cluster_nodes = ["redis://:0rangerY@127.0.0.1:6380", "redis://:0rangerY@127.0.0.1:6381", "redis://:0rangerY@127.0.0.1:6382"]

#Substrate-Blockchain Configuration
#substrate.ws_url = "ws://127.0.0.1:9944"
substrate.ws_url = "wss://node.lockular.in"

#Secret Sharing Configuration
chunk_size = 48
threshold = 1
share_amount = 2
prime = "1602647667098023157650208502760830646118971559180602279760560620305846622963164828915087516998772696148300120393034934719"
thread_number = 5


enable_blockchain = false
#[account]
#name = "Alice"

[logging]
level = "WARN"
#"error" => tracing::Level::ERROR,
#"warn" => tracing::Level::WARN,
#"info" => tracing::Level::INFO,
#"debug" => tracing::Level::DEBUG,
#"trace" => tracing::Level::TRACE,
